#define MAX_N_ENTITIES 1024
#define MAX_N_COLLISIONS MAX_N_ENTITIES* MAX_N_ENTITIES
#define MAX_N_VIEW_RAYS 64
#define MAX_N_DEBUG_PRIMITIVES 1024
#define MAX_ENTITY_NAME_SIZE 64
#define MAX_N_POLYGON_VERTICES 128
#define LARGE_HANDLE_SCALE 0.01
#define SMALL_HANDLE_SCALE 0.005
#define CAMERA_SCROLL_SENSITIVITY 2.0
